version: '3.8'

services:
  mqtt:
    image: eclipse-mosquitto
    container_name: senserx-mqtt
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: senserx-api
    environment:
      - MQTT_SERVER_URL=${MQTT_SERVER_URL}
      - MQTT_USERNAME=${MQTT_USERNAME}
      - MQTT_PASSWORD=${MQTT_PASSWORD}
      - REDIS_URL=redis://redis:6379
    ports:
      - "6868:8080"
    depends_on:
      - mqtt
      - redis

  redis:
    image: redis/redis-stack:latest
    container_name: senserx-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: